#!/usr/bin/env bash

if [ !  -n "$1" ]
then
  echo "error: Parameter project_name not found"
  echo -e "Usage: project-create [PROJECT_NAME]"
  exit 1
fi

projectName="$1"
projectPath="/var/www/$1"

if [ -e "$projectPath" ]
then
   echo "Project projectName already exists"
   exit 1
fi

#create project dir
mkdir $projectPath
chmod 777 $projectPath

#clone project
cd $projectPath;
git clone git@git.shogo.ru:shogo/argilla.git .

#configure project
configTemplate="protected/config/.env.example"
configFile="protected/config/.env"
sed -e "s/project_name/$1/" -e "s/APP_DEBUG=false/APP_DEBUG=true/" -e "s/APP_ENV=prod/APP_ENV=dev/" -e "s/DB_HOST=localhost/DB_HOST=mysql/" $configTemplate > $configFile

#createDBCommand="CREATE DATABASE \\`$projectName\\` CHARACTER SET utf8 COLLATE utf8_general_ci;"
#GRANT ALL ON `$projectName`.* TO `username`@localhost IDENTIFIED BY 'password';
#mysqlCommand="mysql -hmysql -uprog -p123 -e $createDBCommand"
#echo $mysqlCommand

cd /var/www/laradock
docker-compose exec --user=laradock workspace sh -c "mysql -hmysql -uprog -p123 -e 'CREATE DATABASE \`$projectName\` CHARACTER SET utf8 COLLATE utf8_general_ci;' && cd $projectPath && composer install && protected/yiic db applySchema && protected/yiic migrate up --interactive=0 && protected/yiic rbac reset"

nginx-add-project $projectName
