#!/bin/bash

# проверяем файл конфига

# проверяем что вертка масте, если нет запускаем диалог
BRANCH=master
FILE_CONFIG="$PWD/.deploy"

if [ -f "$FILE_CONFIG" ]
then
  source "$FILE_CONFIG"
else
  echo "Config file $FILE_CONFIG not found"
  echo "File variable PROD_USER"
  echo "File variable PROD_SERVER"
  echo "File variable PROD_PROJECT_PATH"
  echo "File variable PROD_OTHER_COMMANDS"
  exit 1
fi;

if [ "$1" = "-p" ]
then
  USER=$PROD_USER
  SERVER=$PROD_SERVER
else
  echo "exmple: deploy -p|-t [-f]"
  echo "-p deploy on production server"
  echo "-t deploy on test server"
  echo "-f force wthout confirm"
  exit 1
fi

echo "Deploing by ssh to $USER@$SERVER"

if [ ! "$2" = "-f" ]
then
  read -r -p "Are you sure? [y/N] " response
  case "$response" in
      [yY][eE][sS]|[yY]) 
  #        do_something
          ;;
      *)
          exit 0
          ;;
  esac
fi

git push origin "$BRANCH:$BRANCH"

ssh "$USER@$SERVER" 'bash -s' -- < /usr/local/bin/script-remote-deploy.sh "$BRANCH" "$PROD_PROJECT_PATH" "$PROD_OTHER_COMMANDS"
